### ISSUE TITLE
Alpha issues (need to split up)

### ISSUE THREAD

**Issue by Noviv** [Noviv/BismarkUnchained#33]
- alpha report
- code cleanup
- minimum nonzero `time_delta`
- visual direction indicator for player
- controller button mapping for shooting (put it on RB or RT)
- out of bounds enemy spawning?
- player shooting limit higher + spawn in less enemies
- enemy+player texture
- controller pause screen
- enemy shoot less bullets
- longer waves
- current+high score tracker
- enemies spawn in screen

**Comment by shraymittal** [comment]
PR open for min nonzero t_d, controller button mapping, player shooting limit higher

**Comment by shraymittal** [comment]
PR #37 closes a number of these issues

**Comment by Noviv** [comment]
issues have been split up, alpha is near complete
