### ISSUE TITLE
Bullet spawn rotation delay

### ISSUE THREAD

**Issue by Noviv** [Noviv/BismarkUnchained#42]
When a bullet is spawned it has an initial rotation, then jumps to the normal rotation. This should be fixed so that the bullet spawns in when (or at least is only visible after) the rotation is set.

**Comment by shraymittal** [comment]
Is this for player bullets, enemy bullets, or both?

**Comment by Noviv** [comment]
> Is this for player bullets, enemy bullets, or both?

I've only seen it happen with player bullets.

**Comment by shraymittal** [comment]
> > Is this for player bullets, enemy bullets, or both?
> 
> I've only seen it happen with player bullets.

Idk if I'm just blind but I really can't see it at all.
I tried making a Sprite.setvisible false right after instancing then Sprite.setvisible true after position and velocity are set.

Theoretically all the processing should be happening on the same frame. It may have something to do with the fact that we never explicitly set global rotation for the player bullets

Like I said I can't really see it either way though
