### ISSUE TITLE
Consistent and defined bullet/bullet collisions

### ISSUE THREAD

**Issue by shraymittal** [Noviv/BismarkUnchained#46]
Bullet/bullet collisions are weird and unpredictable. It seems like the player bullet needs to collide with 3 enemy bullets before it will explode?

Define the behavior and test it to make sure it holds up. I think player bullets should be unaffected by enemy bullets - no collision at all, enemy bullets aren't exploded and the player bullet isn't exploded.

Enemy bullet/enemy bullet collision can behave similarly or differently, just make it consistent and defined.

**Comment by Noviv** [comment]
@shraymittal when the player spawns a bullet, it scales it up by `Vector2(1.4, 1.4)` - when I removed that line bullets collided as expected. I'll look into this, but removing the scaling is a creates consistent collisions

**Comment by shraymittal** [comment]
> @shraymittal when the player spawns a bullet, it scales it up by `Vector2(1.4, 1.4)` - when I removed that line bullets collided as expected. I'll look into this, but removing the scaling is a creates consistent collisions

can we scale up the bullets some other way then?
