### ISSUE TITLE
Enemy types

### ISSUE THREAD

**Issue by shraymittal** [Noviv/BismarkUnchained#48]
Add a few more enemy types.

Some ideas to make them unique:
- Different shapes (I like attack of the geometry, but we can also texture)
- Different colors
- Different patterns of bullet fire: 2+ parallel bullets, a bullet on every side, a bullet on every corner, etc.
- Different bullet shapes/velocities/colors/damage values
- Different speeds/movement behaviors

**Comment by Noviv** [comment]
more or less done, just need boss type
